sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t api-prototype .

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "prototype-apis"
  env: "Prototype-apis-env"
  bucket_name: "elasticbeanstalk-us-east-1-886715373652"
  bucket_path: "prototype-apis"
  on:
    branch: master
  acess_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY