sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t api-prototype .

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "hackathon-tech4th"
  env: "Hackathon-tech4th-env"
  bucket_name: "elasticbeanstalk-us-east-2-334675205829"
  bucket_path: "hackathon-tech4th"
  on:
    branch: master
  acess_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY